script: skip
install: skip
before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
  token:
    secure:61+32Lt4K5DsAbjni5pPZqkR34EiI1LHWFnx3AQEoKm8MMxz3Y9nAkPYrG5Fx1FHhDdshzVihf/zOlSd3UIARfDYsP08kCR7G/xerGTJw9HDN9SF4mC4vTvhFqbTwd98ATebN18GnRjBpDtE6O/Nu1EHQkN8KVgAHQoUBS2NjKKYM0g8DfRRYHdmQBZa7rN5Qeyj1oNuf23QF0ewTF8eHte1H6kuyFY9OoVCMA+8dEGbJ9b6/MYl063gdhHlGViahAIkl8pfIPlDYZjrB3Fl9+qTaYfAyLvQSP6jLpZ+GOvYV6OInSTrj44PM61NKUYOrQ3nE1QFfWKUABay5s7/P6ipO9EfXwGQmEQA9EYMlKpkCpiX23IEzUeXIQpV8ixQ8+qQRIChUMkCHVKwb35SNlqy5i3m5VkPb+XZJKagYj8ukkznWp+lgzawZhSXZHLWGrSCist3wr/s4Rvj5fohKIEm+NNaH/L6YYCJVlN7zNoM9Mr5fIMbJH3YJg7CcnaMA4ED6IsEOwazgyoT0+Sb13eWsgpE7Ao6Cci6N4OoExvXiUa74O+qbdcUh4XDiUkROS7lOGtpUyxac8c/zLpgqJ9tgYnWWFGDxJ6yaiaEcKfCfP5K62U/Ze0jw7FDbeFV5s6MtKz/DMlSyK+RMNAtCeH8WUuWmBEBSRYSFOgz9Y=   
