script: skip
install: skip
before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
env:
  global:
    secure: cDNISF1jiHfvaOXo0V6THOjfMby/LCy1oGCg9ffB/uspZUfwJeMZHrT2TvKsiIF2uJdD4CwR9GUYX2+lXYbpQq/3ZoJubOFklXrUPbFaX2YzHqrQVnPaaGEAAwUQs7tagUxRTEKO7zOqhGjAWWL4HHCRkp2Z7W0SuZ/sOLjQHZffepBryfPVqpI6xzjCIUijyShS4/DF6dc1eYzvtdqyxt+ii7OoMDp0tLcHYS0hhQuY0h5Lpm609s0XgXtsyqAHQoFgm/TGZ+7hwNJngDuODlL1ZdHORsOPm/T79MxesQTblorrQSf8+FoiO0pP14f3WYAVoaOyQ1cdvYuL3lBeU7RnB+m1WnRvIpN2Q8EuPJLZ8LKTlW1nekLjT94+Il56L4O3f3qIf4pt5SPh5npisaFwlqaf8o9V5QLHke/wW2ikL4MTT7FR1cfg7r2WvEYHjDzfupXCTq+M834bv7enKqjDJtZDcwgNIUL0Bik/7LvPmf7sdmidFp6SYyzsAVw/OQpZtqE80yMR8vEiPlAD3SpqhPI0t0FVRAAIoQx6cNguocuDBSXkG/JanCehXCIdS1dA7tq3jtI8APPmXAbRpE+GQ0MMRl2PxWk9zdGkTKj4IZuSmWwB71/F5njx7YYho3rSRD+IRhmFfgQG9UzoLycgn6WTjiN8Bc5LdRTLVX0=
